# Generated by Django 3.2.6 on 2021-08-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('movie_rating', models.CharField(max_length=10)),
                ('movie_year', models.CharField(max_length=5)),
                ('movie_duration', models.CharField(max_length=10)),
                ('movie_description', models.CharField(max_length=700)),
            ],
        ),
    ]
